### ISSUE TITLE
Keycloak Authenticate with Facebook Token

### ISSUE THREAD

**Issue by jstortoise** [keycloak/keycloak-nodejs-admin-client#23] opened 2019-08-15 16:24 UTC
Hi guys, I have a problem with Keycloak authentication with social providers.

Actually, I can do authentication with keycloak username and password.

But some users are registered with facebook accounts.

After getting facebook token from my backend, I'd like to authenticate keycloak by using this token like username and password.

Otherwise, is there any way to get keycloak user's password?

**Comment by edewit** [comment] 2021-11-02 13:37
duplicate of #29

**Closed by edewit** 2021-11-02 13:37 UTC
Labels: enhancement
